package org.yaroslaavl.userservice.exception.error;

public enum ErrorType {

    APPROVAL_REQUIRED,
    ALREADY_REGISTERED,
    AUTH_LOGIN,

    EMAIL_VERIFICATION_CODE_NOT_EQUAL,
    EMAIL_VERIFICATION_EXPIRED,

    FILE_STORAGE,
    IMAGE_UPLOAD,

    KEY_CLOAK_USER_DELETION,
    KEY_CLOAK_USER_CREATION,

    RECRUITER_NO_UPDATE_PERMISSION,
    RECRUITER_REQUEST_CREATED,

    USER_VERIFICATION_NOT_ACCEPTED,

    OBJECT_NOT_FOUND
}
