package org.yaroslaavl.userservice.exception.error;

public enum ErrorType {

    APPROVAL_REQUIRED,
    ALREADY_REGISTERED,
    AUTH_LOGIN,

    FILE_STORAGE,
    IMAGE_UPLOAD,

    KEY_CLOAK_ACTION,

    LANGUAGE_DELETION,
    RECRUITER_NO_UPDATE_PERMISSION,
    RECRUITER_REQUEST_CREATED,

    USER_VERIFICATION_NOT_ACCEPTED,

    ENTITY_NOT_FOUND
}
